### ISSUE TITLE
Consultation on readme file

### ISSUE THREAD

**Issue by yaoshanliang** [DmitryRyumin/WACV-2024-Papers#5]
Thanks for your wonderful collection.

I want to know how did you generate the badge in the readme file. For example, for the `Total Papers`, `Preprint Papers`, did you enter the values manually, or do you have some kind of tool that automatically counts them? 

Besides, for the paper link on [here](https://github.com/DmitryRyumin/WACV-2024-Papers/blob/main/sections/2024/workshops/w_maritime_cv.md), did you input the publisher and link of each paper manually and then generate different badges?

**Comment by DmitryRyumin** [comment]
Hi @yaoshanliang,

All counting is currently done automatically. I just run a local Python script that parses all the generated Markdown files and computes the information.

As for the collection of papers, it's more complicated. The script first parses the paper by its title on arXiv, then the official proceedings from https://openaccess.thecvf.com/menu, and the specific paper. After that, I have to manually check the papers or search for the repo on GitHub to generate the repository links. Also, not all papers can be found on arXiv in manual format, so I have to double-check everything.

Maintaining a high-quality, comprehensive collection requires a combination of automated tools and meticulous manual curation.
